# SPLIT

In [2]:
import numpy as np

In [4]:
array = np.array([[1, 2, 3, 4, 5, 6]])
array

array([[1, 2, 3, 4, 5, 6]])

In [7]:
array_dividido = np.split(array, 3, axis=1)
array_dividido

[array([[1, 2]]), array([[3, 4]]), array([[5, 6]])]

In [11]:
for i, value in enumerate(array_dividido):
    print(f"Parte {i+1}: -> {value}")

Parte 1: -> [[1 2]]
Parte 2: -> [[3 4]]
Parte 3: -> [[5 6]]


In [15]:
# Criar um array 1D com temperaturas diarias de um mês(30 dias)
temperaturas = np.array([30, 32, 31, 29, 28, 27, 26, 
                         25, 24, 23, 22, 21,
                         20, 19, 18, 17, 16,
                         15, 19, 22, 32, 31,
                         19, 28, 27, 16, 25,
                         24, 33, 32, 31, 36])
temperaturas

array([30, 32, 31, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 19, 22, 32, 31, 19, 28, 27, 16, 25, 24, 33, 32, 31, 36])

In [16]:
# Dividir as temperaturas em 4 semanas ( cada semana com 7 dias)
semanas = np.split(temperaturas, 4)
semanas

[array([30, 32, 31, 29, 28, 27, 26, 25]),
 array([24, 23, 22, 21, 20, 19, 18, 17]),
 array([16, 15, 19, 22, 32, 31, 19, 28]),
 array([27, 16, 25, 24, 33, 32, 31, 36])]

In [ ]:
# Temperaturas durante os dias da semana
for i, value in enumerate(semanas):
    print(f"Semana {i+1}: -> {value}")


Semana 1: -> [30 32 31 29 28 27 26 25]
Semana 2: -> [24 23 22 21 20 19 18 17]
Semana 3: -> [16 15 19 22 32 31 19 28]
Semana 4: -> [27 16 25 24 33 32 31 36]


In [ ]:
# media semanal das temperaturas
media_semanal = np.mean(semanas, axis=1)
media_semanal

array([28.5 , 20.5 , 22.75, 28.  ])

In [ ]:
# Média das temperaturas da semana
for i, value in enumerate(media_semanal):
    print(f"Média das temperaturas da Semana {i+1}: -> {value:.2f}ºC")

Média das temperaturas da Semana 1: -> 28.50ºC
Média das temperaturas da Semana 2: -> 20.50ºC
Média das temperaturas da Semana 3: -> 22.75ºC
Média das temperaturas da Semana 4: -> 28.00ºC
