# PESQUISANDO EM ARRAYS

In [1]:
import numpy as np

In [5]:
array = np.array([10, 20, 30, 40, 50])
array

array([10, 20, 30, 40, 50])

In [7]:
# Pesquisando valor 30 no array
posicao = np.where(array==30)
posicao

(array([2]),)

In [8]:
# Criar um array com notas de alunos  
notas = np.array([7.5, 8.0, 6.5, 9.0, 5.5, 7.0, 9.0, 10.0])
notas

array([ 7.5,  8. ,  6.5,  9. ,  5.5,  7. ,  9. , 10. ])

In [13]:
# Pesquisar quais alunos foram aprovados (nota maior que 7)
alunos_aprovados = np.where(notas > 7)
notas[alunos_aprovados]

array([ 7.5,  8. ,  9. ,  9. , 10. ])

In [14]:
nota_maxima = np.max(notas)
nota_minima = np.min(notas)
nota_maxima, nota_minima

(np.float64(10.0), np.float64(5.5))

In [ ]:
indice_maximo = np.argmax(notas)
indice_maximo


np.int64(7)