In [1]:
import numpy as np

In [ ]:
array_1d = np.array([2,3,4,5,6])
print(array_1d.ndim) # Numero de dimensões
print(array_1d.shape) #formato do array
print(array_1d.size) #tamanho do array
print(array_1d)

# Lista de dados, como séries temporais ou coleções de valores

1
(5,)
5
[2 3 4 5 6]


In [ ]:
array_2d = np.array([[1,2,3],[4,5,6]])
print(array_2d.ndim) 
print(array_2d.shape) 
print(array_2d.size) 
print(array_2d)

#Utilizado em matrizes, tabela de dados, imagens em escala de cinza

2
(2, 3)
6
[[1 2 3]
 [4 5 6]]


In [ ]:
array_3d = np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]]])
print(array_3d.ndim)
print(array_3d.shape)
print(array_3d.size)
print(array_3d)

#Imagens em cores (cada matriz representa um canal de cor, como RGB)

3
(1, 3, 4)
12
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]


In [8]:
array_4d = np.zeros((2,3,4,5))
print(array_4d.ndim)
print(array_4d.shape)
print(array_4d.size)
print(array_4d)

4
(2, 3, 4, 5)
120
[[[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]


 [[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]]
