In [1]:
import numpy as np

In [2]:
array = np.array([[1, 2, 3],
                  [4, 5, 6], 
                  [7, 8, 9]])
print(array.ndim)
print(array.shape)
array

2
(3, 3)


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
# Buscando elemento na linha 1 e coluna 2
elemento = array[1, 1]
elemento

np.int64(5)

In [6]:
# Pegar dados na primeira linha
linha0 = array [0, :]
linha0

array([1, 2, 3])

In [8]:
# Pegar dados na primeira coluna
coluna0 = array [:, 1]
coluna0

array([2, 5, 8])

In [ ]:
# Fatiamento de array, para gerar um subarray
subarray = array[0:2, 1:3] # Linhas 0 a 1, Colunas 1 a 2
subarray

array([[2, 3],
       [5, 6]])

In [11]:
mascara = array > 5
mascara

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]])

In [13]:
elementos_maiores_que_5 = array[mascara]
elementos_maiores_que_5

array([6, 7, 8, 9])

In [ ]:
# Modificando elementos do array, atraves de indexação
array[0, 0] = 10
array

array([[10,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])