# Funções universais do NUMPY (uFunc)

In [3]:
import numpy as np

In [4]:
array = np.array([1, 2, 3, 4, 5])
array

array([1, 2, 3, 4, 5])

In [5]:
# Adição
soma = np.add(array, 10)
soma

array([11, 12, 13, 14, 15])

In [7]:
# Subtração
subtracao = np.subtract(array, 5)
subtracao

array([-4, -3, -2, -1,  0])

In [9]:
# Multiplicação
produto = np.multiply(array, 2)
produto

array([ 2,  4,  6,  8, 10])

In [10]:
# Divisão
divisao = np.divide(array, 2)
divisao

array([0.5, 1. , 1.5, 2. , 2.5])

In [ ]:
# Funções trigonométricas
#Seno
seno = np.sin(array)
seno


array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427])

In [ ]:
# Cosseno
cosseno = np.cos(array)
cosseno

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219])

In [ ]:
# Funções estatisticas
# Média
media = np.mean(array)
media

np.float64(3.0)

In [ ]:
# Desvio Padrão
desvio_padrao = np.std(array)
desvio_padrao

np.float64(1.4142135623730951)

In [17]:
# Funções de comparação 
comparacao_maior_3 = array > 3
comparacao_maior_3

array([False, False, False,  True,  True])

In [ ]:
# Combinando funções
resultado = np.sqrt(array) + np.power(array, 2)
resultado

array([ 2.        ,  5.41421356, 10.73205081, 18.        , 27.23606798])

In [ ]:
# Funções expoenciais
exponencial = np.exp(array)
exponencial

In [ ]:
# # Função de logaritmo
logaritmo = np.log(array)
logaritmo

In [ ]:
# Funções de arredondamento
arredondado = np.round(array / 2)
arredondado

In [ ]:
# Função de potência
potencia = np.power(array, 3)
potencia