Copy
- Cria uma nova cópia do array é criada em memória.
Isso significa que as 2 matrizes (original e cópia) são indpendentes uma da outra.

View
- Não é criada uma nova cópia do array na memória.
A view ela compartilha os mesmos dados que o "Array" original.

In [3]:
import numpy as np

In [4]:
array_original = np.array([[1, 2, 3],
                           [4, 5, 6], 
                           [7, 8, 9]])
array_original

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
# Fazendo uma cópia rasa (View) do nosso array original
array_view = array_original[1:, 1:]
array_view

array([[5, 6],
       [8, 9]])

In [ ]:
# Alterando um elemento do array_view
array_view[0, 0] = 98
array_view

array([[98,  6],
       [ 8,  9]])

In [ ]:
# Buscando o array original para verificar se houve alteração, para preservar o array original, não devemos alterar o array_view, pois ele é apenas uma view do array original, ou seja, ele aponta para o mesmo local de memória do array original, então qualquer alteração feita no array_view também afetará o array_original. Para evitar isso, podemos fazer uma cópia profunda (Deep Copy) do array original usando o método copy().

array_original

array([[ 1,  2,  3],
       [ 4, 98,  6],
       [ 7,  8,  9]])

In [9]:
# Usando o método copy() para criar uma cópia profunda do array original
array_copia = array_original.copy()
array_copia

array([[ 1,  2,  3],
       [ 4, 98,  6],
       [ 7,  8,  9]])

In [10]:
# Alterando um elemento do array_copia
array_copia[0, 0] = 99
array_copia

array([[99,  2,  3],
       [ 4, 98,  6],
       [ 7,  8,  9]])