# JOIN


In [1]:
import numpy as np

In [2]:
# Cirando dois arrays 1D

array1 =np.array([1, 2, 3,])
array2 =np.array([4, 5, 6])


In [4]:
# Concatenando os arrays usando np.concatenate()
novo_array = np.concatenate((array1, array2))
novo_array

array([1, 2, 3, 4, 5, 6])

In [5]:
# Criando arrays para nomes e notas

nomes =np.array(['Alice', 'Bob', 'Charlie'])
notas_quimica = np.array([85, 90, 78])
notas_fisica = np.array([80, 85, 70])


In [7]:
# Usando np.vstack() para empilhar verticalmente os arrays de notas
notas_estudantes = np.vstack((nomes, notas_quimica, notas_fisica))
notas_estudantes

array([['Alice', 'Bob', 'Charlie'],
       ['85', '90', '78'],
       ['80', '85', '70']], dtype='<U21')

In [10]:
# Usando np.hstack() para empilhar horizontalmente os arrays de notas
matriz_notas = np.column_stack((notas_quimica, notas_fisica))
matriz_notas

array([[85, 80],
       [90, 85],
       [78, 70]])

In [12]:
# Adicionando uma nova coluna com as médias de notas

media_notas = np.mean(matriz_notas, axis=1)
matriz_final = np.column_stack((matriz_notas, media_notas))
matriz_final

array([[85. , 80. , 82.5],
       [90. , 85. , 87.5],
       [78. , 70. , 74. ]])